#!/bin/bash

set -e

retcode=-1
while (($retcode != 0)); do
  mysql -umysos -h127.0.0.1 -P3306 --password="${QLINK_DB_PASSWORD}" < ./schema.sql
  retcode=${?}
done

export QLINK_DB_USERNAME=mysos

./run
