#!/bin/bash

retcode=-1
while (($retcode != 0)); do
  mysql -umysos -h127.0.0.1 -P3306 --password="${QLINK_DB_PASSWORD}" < ./dev_privileges.sql
  retcode=${?}
  sleep 1
done

retcode=-1
while (($retcode != 0)); do
  mysql -umysos -h127.0.0.1 -P3306 -Dqlink --password="${QLINK_DB_PASSWORD}" < ./schema.sql
  retcode=${?}
  sleep 1
done

export QLINK_DB_USERNAME=mysos

./run
