#!/bin/bash

mvn install:install-file \
  -Dfile=./lib/martyr-1.0.jar \
  -DgroupId=f00f.net.irc \
  -DartifactId=martyr \
  -Dversion="1.0" \
  -Dpackaging=jar \
  -DgeneratePom=true

mvn clean package
