/***************************************************************************
                          qclientconn.h  -  description
                             -------------------
    begin                : Sat Dec 1 2001
    copyright            : (C) 2001 by Keith Henrickson
    email                : flipper@phin.com
 ***************************************************************************/

#ifndef QCLIENTCONN_H
#define QCLIENTCONN_H

#include <tcpconnection.h>

/**This class handles all the TCP communications with the client.
  *@author Keith Henrickson
  */

class QUser;
class QClientConn : public TCPConnection  {
public: 
	QClientConn(TCPManager* pInManager, int nInFD);
	~QClientConn();
  /** No descriptions */
  void TransmitCommand(unsigned char* pbOutCommand, int nOutCommandLen);
private: // Private methods
  /** This is called when the data is ready. */
  void ReceiveData(unsigned char * pbRecBuffer, int nRecBufferLen);
  unsigned short compute_crc(unsigned char *pszPacketDataBuf, int nPacketLen);
private: // Private attributes
  /**  Has the protocol been started on this line yet*/
  bool fProtocolStarted;
  /**  Protocol minor version number*/
  int nProtoMinor;
  /**  Protocol major version number*/
  int nProtoMajor;
  /** Sequence number being used for packets generated by the server. */
  unsigned char nSerSeq;
  /** Client's packet number that may be freed from client's retransmit queue. */
  unsigned char nCliFreeSeq;
  /** The expected packet number that will be received next from the client */
  unsigned char nCliSeq;
  /** This keeps track of our associated user handling object*/
  QUser* pUser;
protected: // Protected attributes
};

#endif
